fix: remaining issues of proxy-first PR
ExchangeUnion/xud-docker-api pull request #21
Opened 2020-12-09 10:22 UTC by reliveyy

This PR tries to fixes these issues:
- [ ] Following network.log once (setup-status)
- [ ] Status fetching timeout
- [ ] Fix the crazy loop when lnd container stopped

2020-12-09 13:10 UTC, raladev requested changes
- [x] setup-status api returns nothing for me, waiting fix from @reliveyy 
![Screenshot from 2020-12-09 16-02-33](https://user-images.githubusercontent.com/29906866/101633910-0072c300-3a39-11eb-800d-6cb93f5d2334.png)

2020-12-09 14:03 UTC, raladev approved these changes

2020-12-09 15:00 UTC, krrprr approved these changes

2020-12-14 15:18 UTC, raladev commented
- [ ] small fix for status api is required - change xud/boltz status to `Waiting for initial sync` instead of `Container is missing` if lnd wallets were not created.  

- Should we change `Syncing 100%' to `Waiting for lndbtc/lndltc`? @krrprr @kilrau

2020-12-14 15:27 UTC, kilrau commented
As just discussed, we want to do these 2 simple fixes:
1. Change lnd sync status "100..o %" -> `Synced 100.00%. Waiting for wallet creation.`
2. If lnd in syncing `xud +  `bolz` + `arby` should display `Waiting for sync.`

2020-12-15 22:27 UTC, merged